### ISSUE TITLE
TypeError: /src/index.js: path must be a string or Buffer

### ISSUE THREAD

**Issue by ctwhome** [avocadowastaken/babel-plugin-direct-import#11]
Sudently I can't run the app anymore. 

packages: 
```
 "webpack": "^3.10.0",
 "babel-core": "^6.26.0",
  "babel-loader": "^7.1.2",
  "babel-plugin-direct-import": "^0.5.0",
```
.babelrc
```
    // Material UI Next, React Router 4, React Virtualized
    // https://www.npmjs.com/package/babel-plugin-direct-import

    // Material UI Next
    ["direct-import", ["material-ui"]],

    // React Virtualized
    ["direct-import", ["react-virtualized"]],

    // React Router 4
    ["direct-import", ["react-router", "react-router-dom"]],
```

error (note: I changed my path for <project-path> to show the error )
```
ERROR in ./src/index.js
Module build failed: TypeError: <project-path>/src/index.js: path must be a string or Buffer
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at fulfillConfigExports (<project-path>/node_modules/babel-plugin-direct-import/src/mapper.js:40:41)
    at prepareConfig.reduce (<project-path>/node_modules/babel-plugin-direct-import/src/index.js:11:22)
    at Array.reduce (<anonymous>)
    at _.memoize (<project-path>/node_modules/babel-plugin-direct-import/src/index.js:10:25)
    at memoized (<project-path>/node_modules/lodash/lodash.js:10566:27)
    at PluginPass.Program (<project-path>/node_modules/babel-plugin-direct-import/src/index.js:34:17)
    at newFn (<project-path>/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (<project-path>/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (<project-path>/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (<project-path>/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (<project-path>/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (<project-path>/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (<project-path>/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (<project-path>/node_modules/babel-traverse/lib/index.js:114:17)
 @ multi ./src/index.js webpack/hot/dev-server webpack-dev-server/client?http://localhost:3000/
```

**Comment by avocadowastaken** [comment]
Hello @ctwhome, you need to define plugin once, e.g: 

```json
{
  "plugins": [
    [
      "direct-import",
      ["material-ui", "react-virtualized", "react-router", "react-router-dom"]
    ]
  ]
}

```

**Comment by ctwhome** [comment]
hi @umidbekkarimov thanks for the tip, I backed up to a previous commit and it is working again. Although it seems to not be a problem to define the plugin more than one... strange. Thanks for the fast response.

**Comment by avocadowastaken** [comment]
@ctwhome can you please provide full content of your `.babelrc` file?

Here is mine working copy:

```json
{
  "presets": [
    "react",
    [
      "env",
      {
        "modules": false,
        "targets": {
          "uglify": true
        }
      }
    ]
  ],
  "plugins": [
    "lodash",
    "date-fns",
    "transform-react-remove-prop-types",
    "syntax-dynamic-import",
    "transform-class-properties",
    "transform-object-rest-spread",
    [
      "transform-runtime",
      {
        "helpers": true,
        "polyfill": false,
        "regenerator": false
      }
    ],
    [
      "direct-import",
      [
        "redux-form",
        "react-router",
        "react-virtualized",
        "react-google-map-components",
        "material-ui",
        {
          "name": "material-ui/svg-icons",
          "indexFile": "material-ui/svg-icons/index.es"
        }
      ]
    ]
  ]
}
```
