### ISSUE TITLE
"Cannot use import statement outside a module" error

### ISSUE THREAD

**Issue by szimek** [avocadowastaken/babel-plugin-direct-import#123]
Hi!

I'm trying to add this plugin to our app. Unfortunately, when I add this plugin, I'm getting the following error:
```
Details:

    .../node_modules/@mui/material/InputAdornment/InputAdornment.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import _objectWithoutPropertiesLoose from "@babel/runtime/helpers/esm/objectWithoutPropertiesLoose";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import React, { useCallback, useMemo, useEffect, forwardRef } from 'react'
        |                                                                           ^
      2 | import { InputAdornment } from '@mui/material'
      3 | import debounce from 'lodash/debounce'
      4 | import cn from 'classnames'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1449:14)
      at Object.<anonymous> (.../components/InputSearch/InputSearch.tsx:1:75)
      at Object.<anonymous> (.../components/InputSearch/InputSearch.test.tsx:3:1)
```

Here's our .babelrc file:
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": "defaults"
        }
      }
    ],
    ["@babel/preset-typescript"],
    ["@babel/preset-react"]
  ],
  "env": {
    "test": {
      "presets": [
        [
          "@babel/preset-env",
          { "targets": { "node": "current" } }
        ]
      ]
    }
  },
  "plugins": [
    [
      "babel-plugin-direct-import",
      {
        "modules": [
          "@mui/lab",
          "@mui/system",
          "@mui/material",
          "@mui/icons-material"
        ]
      }
    ]
  ]
}
```
Of course, it works fine (though very slow) without this plugin. `babel-plugin-import` also works fine.

**Comment by avocadowastaken** [comment]
Hey @szimek ! 

looks like the error was produced during the `jest` call. And since it doesn't support ES modules by default, you should not use this transform for it.

**Comment by szimek** [comment]
@avocadowastaken Thanks for the response!
